storage_file: storage.csv
update_interval: 5m
services:
  - name: github
    provider: statuspage
    url:  https://kctbh9vrtdwd.statuspage.io/api/v2/
  - name: bitbucket
    provider: statuspage
    url: https://bqlf8qjztdtr.statuspage.io/api/v2/
  - name: rubygems
    provider: statuspage
    url: https://pclby00q90vc.statuspage.io/api/v2/
  - name: cloudflare
    provider: statuspage
    url: https://yh6f0r4529hb.statuspage.io/api/v2/
